### ISSUE TITLE
Discussion: handling different loss types (API choices)

### ISSUE THREAD

**Issue by cassiofragadantas** [cohenjer/benchmark-nmf#10]
The proper way of handling different loss functions remains an open question for this benchmark. 
It is important to identify two similar but distinct things: (i) the loss purely as a measure of quality; (ii) the loss to be optimized by a solver.

Some identified options are:

1) (currently implemented) A parameter in `objective.py` determines the tracked loss (i.e., the one used in the stopping criterion). Then another parameter in each solver determines the loss to be optimized. This option is more flexible, since it allows the choice of any combination by the user. However, it might be overly complicated, since duplicates the parameters. 

2) A parameter in `objective.py` only. It would define the tracked loss and would be sent to the solvers via the `set_objective` function, thus also defining the loss to be optimized. This centralizes the loss choice in a single parameter, but is less flexible as one wouldn't be able to choose distinct loss types for (i) and (ii) (is this case actually relevant?).

3)  A parameter in the solvers only. In this case, all the loss types could be computed in `objective.py` every time. The solver would specify which objective key to be used in the stopping criterion (*). This allows to always have a plot for every loss type, independently of the fact that the solvers optimized that particular loss or not. A potential disadvantage would be the higher computational effort of computing all losses every time.

(*) possible since benchopt/benchopt#461. By the way, options 1 and 2 can be seen as somewhat outdated, since the solver can now choose which objective key to be used in the stopping criterion.

What are your thoughts on this? Any other propositions?

**Comment by tomMoral** [comment]
I am strongly in favor for 3.  I think the computational effort is minimal (and not the bottleneck) and this allows to compare all results consistently.

To me, the objective should not change too much between different runs so 1 and 2 seem a bit a stretch of the API but I am happy to hear your thoughts about that.

**Comment by cohenjer** [comment]
I think we should moderate the fact that computing the cost is cheap. For instance with Frobenius loss/cost, a typical evaluation of the gradient with model $X\approx WH$ involves computing $W^TX$, $W^TW$ similarly for $H$. Typically $W^TX$ is the costly operation, with O(mnr) if $X$ is $m\times n$ . Computing the cost involves computing $WH$ which also involves O(mnr) operations (there are other ways to compute the cost but the complexity is still the same overall).

So if we compute a bunch of costs for all algorithms, somehow we may end up computing losses with complexity similar or larger than iterations of the algorithms. 

On the other hand, we could cover 3 using 1., with a parameter `all` active by default which would mean all the losses are computed. This way we allow for flexibility as in solution 1., but the default is 3. in practice (though we still have parameters in the objective; I don't think they would add too much complexity).

**Comment by tomMoral** [comment]
By default, we compute the loss on a log scale  relative to the iterations. Moreover, we can leverage the fact that for many loss, we will actually need $X$, which we can compute only once. So I would be surprise to see that the loss is actually the bottleneck.

What I dislike in 1 is that it makes the benchmark more complex. But if you feel it is better, why not :)

**Comment by cohenjer** [comment]
OK I am convinced :p we can implement 3 !

**Comment by cohenjer** [comment]
Fixed by #13
